#!/bin/bash

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

scp ${dir}/build/release/bin/focusd $1:/opt/focus/focusd
scp ${dir}/build/release/bin/focus-blockchain-export $1:/opt/focus/focus-blockchain-export
scp ${dir}/build/release/bin/focus-wallet-rpc $1:/opt/focus/focus-wallet-rpc

