#!/bin/bash

reset

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FOCUS_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/env
source ${BUILDER_DIR}/helpers
source ${BUILDER_DIR}/linux-helpers

detectversion
detectos

mkdir -p ${BUILDER_DIR}/build/dev/$1
cd ${BUILDER_DIR}/build/dev/$1
cmake -D CMAKE_BUILD_TYPE=$1 -D BUILD_TAG=${FOCUS_BUILD_DISTRO}-${FOCUS_BUILD_DISTRO_VERSION} ../../../..
make -j6
