#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FOCUS_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/env
source ${BUILDER_DIR}/helpers

detectos
detectversion

mkdir -p ${BUILDER_DIR}/build/release
cd ${BUILDER_DIR}/build/release
cmake -D CMAKE_BUILD_TYPE=release -D STATIC=ON -D BUILD_TAG=${FOCUS_BUILD_DISTRO}-${FOCUS_BUILD_DISTRO_VERSION} -D ARCH="x86-64" -G "MSYS Makefiles" ../../..
make -j4
